name: R Package CI

on:
  push:
    branches:
      - main  # Modify if you use a different branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Use the appropriate runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x  # Use the desired R version

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
