on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
        
      - name: Install R version 4.x
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x

      - name: Install dependencies from lockfile
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          profile: '"dev"'

      - name: Run R CMD CHECK
        uses: r-lib/actions/check-r-package@v2
