name: R Package CI

on:
  push:
    branches:
      - main  # Modify if you use a different branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Use the appropriate runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x  # Use the desired R version

      - name: Install package dependencies
        run: Rscript -e 'install.packages(c("devtools"))'

      - name: Check R package
        run: Rscript -e 'devtools::check()'

      - name: Build R package
        run: Rscript -e 'devtools::build()'
        
      - uses: actions/upload-artifact@v3
        with:
          path: "*.tar.gz"
