on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3

      # system dependencies for building R packages
      - name: Install curl development headers
        run: sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
        
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - uses: r-lib/actions/check-r-package@v2
